apiVersion: scan.ahmali3.github.io/v1alpha1
kind: ClusterScan
metadata:
  name: vulnerability-scan
spec:
  image: aquasec/trivy:latest
  target: python:3.9
  command:
    - trivy
    - image
    - --severity
    - HIGH,CRITICAL
    - python:3.9
